name: API CI
#on: [push]
on:
  push:
    paths:
      - './api/**'
      - '.github/workflows/api-ci.yml'

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        width:
          node-version: 18.1.0
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test
